[libdefaults]
    default_realm = CORP.EXAMPLE.ORG
    dns_lookup_kdc = false
    dns_lookup_realm = false

[realms]
    CORP.EXAMPLE.ORG = {
        kdc = 54.174.178.120
        admin_server = 54.174.178.120
    }

[domain_realm]
    corp = CORP.EXAMPLE.ORG
    .corp = CORP.EXAMPLE.ORG
