package sip

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/andrew-aiken/checks"

	"github.com/emiago/sipgo"
	"github.com/emiago/sipgo/sip"
	"github.com/icholy/digest"
)

// inviteSDP is a minimal static SDP offer used when placing a call.
// No real media is exchanged, so the port does not need to be reachable.
const inviteSDP = "v=0\r\n" +
	"o=- 0 0 IN IP4 0.0.0.0\r\n" +
	"s=-\r\n" +
	"c=IN IP4 0.0.0.0\r\n" +
	"t=0 0\r\n" +
	"m=audio 40000 RTP/AVP 0\r\n" +
	"a=rtpmap:0 PCMU/8000\r\n"

type Definition struct {
	// IP or hostname of the system
	Host string `json:"host" optiontype:"required"`
	// sip port
	Port uint16 `json:"port" default:"5060"`
	// Connection transport method
	Transport string `json:"transport" default:"udp"`
	// Username extension
	Username string `json:"username"`
	// Extensions authentication secret
	Password string `json:"password"`
	// Extension to dial
	Callee string `json:"callee" default:""`
	// Shared configuration across all checks
	checks.SharedDefinition
}

// Run performs a sip check
func (d Definition) Run(ctx context.Context, static checks.StaticConf) (result checks.Results) {
	result = checks.Results{
		Timestamp: time.Now(),
	}

	definitionBytes, err := checks.TemplateDefinition(d, static)
	if err != nil {
		result.Message = fmt.Sprintf("internal error templating definition: %s", err)
		return
	}

	var definition Definition
	err = json.Unmarshal(definitionBytes, &definition)
	if err != nil {
		result.Message = fmt.Sprintf("internal error unmarshaling templated definition: %s", err)
		return
	}

	// Setup user agent
	ua, err := sipgo.NewUA(
		sipgo.WithUserAgent(definition.Username),
	)
	if err != nil {
		result.Message = fmt.Sprintf("failed to setup sip user agent: %s", err.Error())
		return
	}

	// Setup Client
	client, err := sipgo.NewClient(ua)
	if err != nil {
		result.Message = fmt.Sprintf("failed to setup sip client: %s", err.Error())
		return
	}
	defer func() {
		clientCloseErr := client.Close()
		if result.Passed && clientCloseErr != nil {
			result.Message = "Error closing sip client: " + clientCloseErr.Error()
			result.Passed = false
		}
	}()

	ctx, cancel := context.WithTimeout(ctx, time.Duration(definition.Timeout)*time.Second)
	defer cancel()

	portString := strconv.Itoa(int(definition.Port))
	address := net.JoinHostPort(definition.Host, portString)

	if definition.Callee == "" {
		passed, message := registerClient(ctx, client, definition, address)
		result.Passed = passed
		result.Message = message
		return
	}

	if definition.Username != "" {
		passed, message := registerClient(ctx, client, definition, address)
		if !passed {
			result.Message = message
			return
		}
	}

	passed, message := placeCall(ctx, client, definition, address)
	result.Passed = passed
	result.Message = message
	return
}

// registerClient performs a REGISTER request
func registerClient(ctx context.Context, client *sipgo.Client, definition Definition, address string) (passed bool, message string) {
	recipient := sip.Uri{}
	err := sip.ParseUri(fmt.Sprintf("sip:%s@%s", definition.Username, address), &recipient)
	if err != nil {
		return false, fmt.Sprintf("failed to parse uri: %s", err.Error())
	}

	req := sip.NewRequest(sip.REGISTER, recipient)
	req.AppendHeader(
		sip.NewHeader("Contact", fmt.Sprintf("<sip:%s@%s>", definition.Username, definition.Host)),
	)
	req.SetTransport(strings.ToUpper(definition.Transport))

	// Send request to register client
	tx, err := client.TransactionRequest(ctx, req, sipgo.ClientRequestRegisterBuild)
	if err != nil {
		return false, fmt.Sprintf("failed to create register transaction: %s", err.Error())
	}
	defer tx.Terminate()

	res, err := getResponse(ctx, tx)
	if err != nil {
		return false, fmt.Sprintf("did not get registration response: %s", err.Error())
	}

	if res.StatusCode == sip.StatusUnauthorized {
		// Get WwW-Authenticate
		wwwAuth := res.GetHeader("WWW-Authenticate")
		chal, parseErr := digest.ParseChallenge(wwwAuth.Value())
		if parseErr != nil {
			return false, "Failed to parse challenge: " + parseErr.Error()
		}

		// Reply with digest
		cred, digestErr := digest.Digest(chal, digest.Options{
			Method:   req.Method.String(),
			URI:      recipient.Host,
			Username: definition.Username,
			Password: definition.Password,
		})
		if digestErr != nil {
			return false, "Failed to generate credential digest: " + digestErr.Error()
		}

		newReq := req.Clone()
		newReq.RemoveHeader("Via") // Must be regenerated by transport layer
		newReq.AppendHeader(sip.NewHeader("Authorization", cred.String()))

		authTx, authErr := client.TransactionRequest(ctx, newReq, sipgo.ClientRequestIncreaseCSEQ, sipgo.ClientRequestAddVia)
		if authErr != nil {
			return false, "Failed to create authentication transaction: " + authErr.Error()
		}
		defer authTx.Terminate()

		res, authErr = getResponse(ctx, authTx)
		if authErr != nil {
			return false, "Did not get authentication response: " + authErr.Error()
		}
	}

	if res.StatusCode != sip.StatusOK {
		return false, "Failed to register client"
	}

	return true, ""
}

// placeCall sends an INVITE to the Callee
func placeCall(ctx context.Context, client *sipgo.Client, definition Definition, address string) (passed bool, message string) {
	calleeRecipient := sip.Uri{}
	err := sip.ParseUri(fmt.Sprintf("sip:%s@%s", definition.Callee, address), &calleeRecipient)
	if err != nil {
		return false, fmt.Sprintf("failed to parse callee uri: %s", err.Error())
	}

	callerID := definition.Username
	if callerID == "" {
		callerID = "anonymous"
	}
	contactHDR := sip.ContactHeader{Address: sip.Uri{User: callerID, Host: definition.Host}}
	dialogCli := sipgo.NewDialogClientCache(client, contactHDR)

	dialog, err := dialogCli.Invite(ctx, calleeRecipient, []byte(inviteSDP), sip.NewHeader("Content-Type", "application/sdp"))
	if err != nil {
		return false, fmt.Sprintf("failed to send invite to %s: %s", definition.Callee, err.Error())
	}

	// This only needs to confirm the call gets past authentication, not that anyone answers.
	err = waitAnswer(ctx, dialog, definition)
	if err == nil {
		// Call was answered; hang up rather than staying on the line.
		if ackErr := dialog.Ack(ctx); ackErr != nil {
			return false, fmt.Sprintf("failed to ack call to %s: %s", definition.Callee, ackErr.Error())
		}

		if byeErr := dialog.Bye(context.Background()); byeErr != nil {
			return false, fmt.Sprintf("error hanging up call to %s: %s", definition.Callee, byeErr.Error())
		}

		return true, ""
	}

	if errors.Is(err, errNoCallResponse) {
		return false, fmt.Sprintf("call to %s got no response at all: %s", definition.Callee, err.Error())
	}

	if errors.Is(err, context.DeadlineExceeded) {
		// Still ringing when the timeout canceled it: accepted, not rejected for lacking auth.
		return true, ""
	}

	// WaitAnswer returns this as *ErrDialogResponse, not ErrDialogResponse.
	var dialogErr *sipgo.ErrDialogResponse
	if errors.As(err, &dialogErr) {
		if isAuthRejection(dialogErr.Res.StatusCode) {
			return false, fmt.Sprintf("call to %s was rejected: %d %s", definition.Callee, dialogErr.Res.StatusCode, dialogErr.Res.Reason)
		}

		// Rejected for a reason unrelated to authentication (e.g. callee does not exist).
		return true, ""
	}

	return false, fmt.Sprintf("call to %s failed: %s", definition.Callee, err.Error())
}

// cancelGracePeriod bounds how long to wait for WaitAnswer to react once ctx expires.
// A call that received at least one response cancels almost immediately; one that received
// none at all falls back to the SIP stack's own ~32s retransmission timeout (Timer_B), which
// would otherwise make this check ignore definition.Timeout entirely.
const cancelGracePeriod = 5 * time.Second

var errNoCallResponse = errors.New("no response received before timeout")

// waitAnswer wraps dialog.WaitAnswer so a destination that never sends any response at all
// cannot hold the check open past definition.Timeout plus a short grace period.
func waitAnswer(ctx context.Context, dialog *sipgo.DialogClientSession, definition Definition) error {
	resultCh := make(chan error, 1)
	go func() {
		resultCh <- dialog.WaitAnswer(ctx, sipgo.AnswerOptions{
			Username: definition.Username,
			Password: definition.Password,
		})
	}()

	select {
	case err := <-resultCh:
		return err
	case <-ctx.Done():
	}

	select {
	case err := <-resultCh:
		return err
	case <-time.After(cancelGracePeriod):
		return errNoCallResponse
	}
}

func isAuthRejection(statusCode int) bool {
	switch statusCode {
	case sip.StatusUnauthorized, sip.StatusForbidden, sip.StatusProxyAuthRequired:
		return true
	default:
		return false
	}
}

func getResponse(ctx context.Context, tx sip.ClientTransaction) (*sip.Response, error) {
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	case <-tx.Done():
		return nil, fmt.Errorf("transaction died")
	case res := <-tx.Responses():
		return res, nil
	}
}

var transportProtocols = []string{"", "UDP", "TCP"}

// Validate checks if the sip definition is valid
func (d Definition) Validate() (passed bool, message string) {
	if d.Host == "" {
		return false, "Host needs to be defined"
	}

	if !slices.Contains(transportProtocols, strings.ToUpper(d.Transport)) {
		return false, "Invalid SIP transport protocol specified"
	}

	return true, ""
}
